- README.md
Since we included more directories, we have not yet updated the README to describe them. Update it.
Inspect the README rendering in GitHub.
> Update the README to contain more folders

- README.md
Add a brief description of how to build our code to README.md
View the rendered README.md in GitHub
> Add "Building" section to our README

- .github/workflows/triggers-docs-rebuild.yml
- README.md
When the docs here change, we want to rebuild docs.resim.ai
> add a workflow that triggers a rebuild of docs.resim.ai

- docs/resim/curves/index.md
Currently broken on https://docs.resim.ai/open-core/curves/
> docs - make links in curves relative

- WORKSPACE
`bazel fetch //...` was failing, not sure for how long. This fixes that.
`bazel fetch //...`
> Fix bazel fetch

- WORKSPACE
- requirements_lock.txt
- transitive_deps.bzl
Adds Pandas with performance dependencies
`bazel fetch //...` works.
> Add pandas dependency

- resim/metrics/proto/metrics.proto
Adds fun new features to metrics. Don't land without mentioning, as we need to rerelease go bindings.
`bazel build //resim/metrics/proto/...`
> Add two new minor features to the metrics

- resim/examples/sim_runner/build.sh
- resim/examples/sim_runner/test_run.sh
Make it so the example image can be run outside of the dev docker container also, and improve the comments.
```bash
./resim/examples/sim_runner/build.sh
./resim/examples/sim_runner/test_run.sh
```
> Make some small improvements to the example image

- .trunk/config/.mypy.ini
- .trunk/trunk.yaml
- resim/metrics/BUILD
- resim/transforms/python/quaternion_test.py
- resim/transforms/python/se3_python_test.py
- resim/transforms/python/so3_python_test.py
Add mypy to trunk to check python typing
```
trunk check
```
> Add mypy type checking

- README.md
- resim/curves/two_jet.hh
- resim/examples/assert_and_status.cc
- resim/examples/curves.cc
- resim/examples/gaussian.cc
- resim/examples/liegroups.cc
- resim/examples/match.cc
- resim/examples/output_parameters.cc
- resim/examples/sim_runner/README.md
- resim/examples/time.cc
- resim/examples/trajectory.cc
- resim/examples/view.cc
> update docs links to docs.resim.ai/open-core/

- .github/workflows/release.yml
Add missing "with" keyword to release workflow.
> Add missing line to release workflow

- resim/toolchain/check_python_test.py
Fix trunk errors in `resim/toolchain/check_python_test.py`.
```
trunk check --all
```
> Fix trunk errors

- .trunk/.gitignore
- .trunk/trunk.yaml
Revert #77's upgrade of trunk while we fix issues that the newer version finds on unchanged paths.
CI checks cover.
> Temporarily downgrade trunk

- version.bzl
This should have been done before releasing, but it's better late than never.
> Increment the version number

- version.bzl
Move version to 0.0.3 in preparation for releasing.
> Bump version to 0.0.3

- .trunk/trunk.yaml
- resim/metrics/proto/generate_test_metrics.py
- resim/metrics/proto/metrics.proto
- resim/metrics/proto/validate_metrics_proto.py
- resim/metrics/proto/validate_metrics_proto_test.py
- resim/metrics/python/metrics_utils.py
- resim/metrics/python/metrics_utils_test.py
- resim/metrics/python/metrics_writer.py
- resim/metrics/python/metrics_writer_test.py
> Revert "Add new BLOCK failure status"

- version.bzl
Increment the version for version 0.0.6
```bash
```
> Prepare release v0.0.6

- docs/resim/metrics/batch_metrics.md
- resim/metrics/BUILD
- resim/metrics/fetch_job_metrics.py
- resim/metrics/fetch_job_metrics_test.py
Docs and some helpers for batch metrics.
`bazel test //resim/metrics:fetch_job_metrics_test`.
> Batch metrics docs

- resim/math/BUILD
- resim/math/newton_solver.hh
- resim/math/newton_solver_test.cc
Add Newton's Method to the repository.
```bash
bazel test //resim/math:newton_solver_test
```
> Add Newton's Method

- deps.bzl
Upgrade this dependency.
```bash
```
> Upgrade au dependency to 0.3.4

- version.bzl
> Bump to version 0.0.7

- resim/actor/BUILD
Make the actor target have public visibility.
```
```
> Make the actor target public

- resim/simulator/standard_frames.hh
- resim/simulator/standard_topics.hh
Adds a couple of new frames/topics, in particular ECEF frame.
N/A
> Add a new frame and topic

- resim/ros2/resim_log_from_ros2_python.cc
- resim/ros2/resim_log_from_ros2_test_helpers_python.cc
- resim/testing/mock_server.cc
Remove `#include <iostream>` from a few places where it is not necessary.
```bash
```
> Remove un-needed headers

- version.bzl
Update the version to 0.0.9 in preparation for release.
```
```
> Update version to 0.0.9

- version.bzl
Increment the version to 0.0.10.
```bash
```
> Increment version to 0.0.10

- bazel_registry/modules/libuuid/2.39.3/MODULE.bazel
- bazel_registry/modules/libuuid/2.39.3/patches/add_build_file.patch
- bazel_registry/modules/libuuid/2.39.3/patches/module_dot_bazel.patch
- bazel_registry/modules/libuuid/2.39.3/source.json
- bazel_registry/modules/libuuid/metadata.json
Add libuuid to registry in preparation for making it hermetic.
Run tests on https://github.com/resim-ai/open-core/pull/136
> Add libuuid to registry

- .devcontainer/Dockerfile
> Update Devcontainer Go Version

- deps.bzl
Updates the open core repo to use the latest version of the ReSim Python Client.
```
```
> Update Python Client

- resim/metrics/python/metrics.py
- resim/metrics/python/metrics_test.py
- resim/metrics/python/metrics_utils.py
- resim/metrics/python/metrics_utils_test.py
- resim/metrics/python/metrics_writer.py
- resim/metrics/python/metrics_writer_test.py
- resim/metrics/python/unpack_metrics.py
- resim/metrics/python/unpack_metrics_test.py
Expands the metrics data class to add event_metric flag.
```
```
> Set Event Metric Field

- resim/auth/python/device_code_client.py
- resim/auth/python/device_code_client_test.py
- resim/geometry/python/polygon_distance_test.py
- resim/metrics/dice_coefficient.py
- resim/metrics/dice_coefficient_test.py
- resim/metrics/fetch_metrics_urls.py
- resim/metrics/fetch_metrics_urls_test.py
- resim/metrics/get_metrics_proto.py
- resim/metrics/get_metrics_proto_test.py
- resim/ros2/resim_log_from_ros2_python_test.py
- resim/toolchain/check_python_test.py
- resim/transforms/python/geodetic_python_test.py
- resim/transforms/python/quaternion_test.py
- resim/transforms/python/se3_python_test.py
- resim/transforms/python/so3_python_test.py
Since we added python linting, we haven't run `trunk fmt --all`. Remedy this.
```bash
```
> Format all files

- .github/workflows/build-push-default-reports-build.yml
Fixes an issue with a workflow run on push to main
N/A
> Fix Github Workflow

- docs/resim/assert/index.md
- docs/resim/curves/index.md
- docs/resim/curves/rigid_body_state.md
- docs/resim/index.md
- docs/resim/math/gaussian.md
- docs/resim/metrics/batch_metrics.md
- docs/resim/metrics/metrics_builds.md
- docs/resim/metrics/metrics_data.md
- docs/resim/ros2/index.md
- docs/resim/time/time.md
- docs/resim/transforms/using_liegroups.md
- docs/resim/utils/output_parameters.md
- docs/resim/visualization/index.md
Added color coding for code blocks.
> Color-coding for code blocks

- .github/workflows/build-push-default-reports-build.yml
- resim/metrics/default_report_metrics.py
Improve axis labels on the job status per batch chart:
https://app.resim.ai/projects/72d84a89-e36d-463d-b875-dc2776f36a5f/reports/c94303bd-6f82-47e4-b739-a37c0bbe80ff
Build/push a report build and run it to verify the axes labels are now as desired.
> Fix x axis label in report metrics

- .github/workflows/build-sim-image.yml
- resim/simulator/BUILD
Push the drone simulator automatically on commit to `main`.
https://github.com/resim-ai/open-core/actions/runs/10407277225/job/28823459637
> Push Drone Sim Image

- bazel_registry/modules/resim-python-client/b39d98f0e0ee9c213d5279af7f648e81e1693a92/MODULE.bazel
- bazel_registry/modules/resim-python-client/b39d98f0e0ee9c213d5279af7f648e81e1693a92/source.json
Make an update to the registry entry for resim-python-client so we can depend on it.
Tested updating the version on another branch.
> Update registry entry for resim-python-client

- .github/workflows/lint-and-codecov.yml
- .github/workflows/release.yml
- .trunk/trunk.yaml
- resim/metrics/python/metrics.py
- resim/metrics/python/metrics_test.py
- resim/metrics/python/metrics_utils.py
- resim/metrics/python/metrics_writer.py
- resim/metrics/python/unpack_metrics.py
Fix all the mypy errors we've been encountering and re-activate the check.
```bash
trunk check --all
```
> Fix mypy issues and re-activate

- bazel_registry/modules/resim-python-client/a36edc3292b713406b2aea1d42b089dfc68234a3/source.json
> Fix Integrity Hash

- docs/resim/metrics/events.md
> Fixes a small typo in the event metrics docmentation

- .github/workflows/add_go_bindings.sh
- pkg/extra_requires.txt
- requirements.txt
* Update the go bindings script so it's not tripped up by the remote cache.
* Tweak some dep versions
N/A
> Make a few small tweaks so we can successfully release

- resim/metrics/default_report_metrics.py
- resim/metrics/python/metrics.py
- resim/metrics/python/metrics_writer.py
- resim/metrics/python/metrics_writer_test.py
- resim/metrics/resim_style.py
- Redefine metrics dataclass decorator so MyPy stops whining so much
- Use BatchwiseBarChart for `test_status_over_time` metric in default report metrics
> Use BatchwiseBarChart in default report metrics & fix builder completion

- resim/metrics/default_report_metrics.py
> default_report_metrics: fix timestamp calculation for batchwise bar chart

- README.md
- docs/resim/index.md
- docs/resim/metrics/batch_metrics.md
- docs/resim/metrics/metrics_builds.md
- docs/resim/metrics/metrics_writer.md
> More metrics docs updates

- .github/workflows/release.yml
- .trunk/trunk.yaml
- bazel_registry/update_open_core.py
- resim/auth/python/check_expiration.py
- resim/auth/python/device_code_client.py
- resim/auth/python/username_password_client.py
- resim/converter/fuzz_helpers.hh
- resim/dynamics/aerodynamics/rigid_body_aerodynamics.cc
- resim/metrics/default_report_metrics.py
- resim/metrics/dice_coefficient_test.py
- resim/metrics/fetch_all_pages.py
- resim/metrics/fetch_job_metrics.py
- resim/metrics/fetch_metrics_urls.py
- resim/metrics/proto/generate_test_metrics.py
- resim/metrics/proto/validate_metrics_proto.py
- resim/metrics/python/metrics.py
- resim/metrics/python/unpack_metrics.py
- resim/orchestration/kickoff_report_test.py
- resim/transforms/liegroup_concepts.hh
- resim/utils/integer_power.cc
- resim/utils/integer_power.hh
- Forced release pipeline to fetch deps before linting
- Updated all of the linters except `clang-tidy` (🙈) and `buildifier` (needs to match bazel version)
> Upgrade linters and fix issues

- .github/workflows/build-push-log-ingest-build.yml
- MODULE.bazel
- resim/builds/log-ingest/BUILD
- resim/builds/log-ingest/entrypoint.sh
> Log Ingest Build

- resim/metrics/default_report_metrics.py
- resim/metrics/fetch_all_pages_test.py
- resim/metrics/fetch_job_metrics.py
- resim/metrics/fetch_metrics_urls.py
- resim/metrics/fetch_report_metrics.py
Fix some issues that CI didn't complain about on the last PR.
https://github.com/resim-ai/open-core/actions/runs/13849373449/job/38753896280
```
trunk check --all --filter mypy 
```
> Fix up mypy

- resim/metrics/proto/validate_metrics_proto.py
- resim/metrics/proto/validate_metrics_proto_test.py
> PRO-194: Add scalar NaN validator 

- resim/metrics/python/emissions.py
- resim/metrics/python/emissions_test.py
- Add `event` argument to `emit` API which sets `$metadata.event` to signify to the datalake that this is an event emission.
> PRO-204: Add `$metadata.event` field to event emissions

- resim-python-client/openapi.yaml
- resim/metrics/fetch_report_metrics_test.py
- resim/orchestration/resim_python_client_mocks.py
> Bump OpenAPI spec

- resim-python-client/openapi.yaml
> Another OpenAPI spec bump
