.devcontainer/run.sh, .devcontainer/run_dotfiles.sh, .devcontainer/run_dotfiles_local.sh, .devcontainer/run_local.sh
This PR assumes that users cloning open-core, will fairly regularly rename the directory to 
something more meaningful to them. In this case it would be nice if the change were 
reflected in the devcontainer workflow.
There is a slight fragility to this implementation in that the user could call `.devcontainer/*` 
from another directory e.g. `../devcontainer/*`, but we are already making use of `$(pwd)` 
so this at least does not make the situation worse.
1. Rename `open-core` e.g. `mv open-core test-core`
2. Run `.devcontainer/run.sh` and verify that the working directory is `test_core`
3. Repeat for other affected scripts
=> "Devcontainer scripts allow for users renaming their base dir"

docs/resim/assert/index.md, docs/resim/curves/index.md, docs/resim/curves/rigid_body_state.md, docs/resim/index.md, docs/resim/math/gaussian.md, docs/resim/time/time.md, docs/resim/transforms/using_liegroups.md, docs/resim/utils/match.md, docs/resim/utils/output_parameters.md, docs/resim/visualization/index.md
We renamed out repo from re-core to open-core, so we need to propagate this change to the docs.
Asana task: https://app.asana.com/0/1205228215063249/1205229151902156/f
Search the docs for references to re-core and confirm that they are no longer there.
Search the docs for references to open-core and confirm that they are there.
=> Replace references to re-core in the docs with open-core

resim/examples/assert_and_status.cc, resim/examples/liegroups.cc
Get rid of some pesky warnings that crop up when building the examples.
```bash
bazel build //resim/examples/...
```
=> Remove unused variable warnings from examples

WORKSPACE, deps.bzl, resim/third_party/ros2/BUILD, resim/third_party/ros2/flto.patch, resim/third_party/ros2/ros2_test.cc, ros2_setup_1.bzl, ros2_setup_2.bzl, transitive_deps.bzl
Add mvukov/rules_ros2 as a dependency.
```
bazel test //resim/third_party/ros2:ros2_test
```
=> Add rules_ros2 as a dependency so we can link ros2 libraries

deps.bzl
Make sure that dependencies of this repo can properly access a patch needed for building ros2
Build in a private ReSim repo which depends on `open-core`:
```
bazel build //...
```
=> Make sure ros2 patch is properly accessible to deps

.devcontainer/Dockerfile
A recommended workflow is for users to push build images to ECR, which means we need to provide the AWS cli for auth.
=> add AWS cli to Docker image (needed for ECR auth)

.gitignore
Add .swp and .swo files to .gitignore.
Open some files in vim and run `git status` to verify that no temporary files show up.
=> Ignore vim temporary files in .gitignore

.devcontainer/Dockerfile
So users of our pubic image get the CLI by default.
[Asana task](https://app.asana.com/0/1205228215063249/1205253425039961/f)
```
.devcontainer/build.sh
.devcontainer/run_local.sh
resim
```
=> Add resim CLI to the public docker image

.devcontainer/Dockerfile
Add trunk to the open core development container.
Build the container locally to verify that it works.
```bash
./.devcontainer/build.sh
```
Check that trunk is installed in the resulting container.
```
./.devcontainer/run_local.sh
trunk check
```
=> Add trunk to the open core devcontainer

.gitignore, deps.bzl, resim/third_party/vision_msgs/BUILD, resim/third_party/vision_msgs/vision_msgs.BUILD
Add `ros-perception/vision_msgs` as a dependency.
```bash
bazel build @vision_msgs//:cpp_vision_msgs
```
=> Add vision_msgs to open-core

resim/time/BUILD, resim/time/timestamp.hh, resim/time/timestamp_test.cc, resim/utils/BUILD, resim/utils/mcap_test_helpers.cc, resim/utils/mcap_test_helpers.hh, resim/utils/mcap_test_helpers_test.cc, resim/utils/snippet_mcap.cc, resim/utils/snippet_mcap.hh, resim/utils/snippet_mcap_test.cc, resim/utils/trim_mcap.cc
Add a command line tool which allows a user to trim an MCAP log to a specific time interval. In other words, this removes all messages that are before the start time and all messages which aren't before the end time.
```bash
bazel test //resim/utils:mcap_test_helpers_test
bazel test //resim/utils:snippet_mcap_test
bazel run //resim/utils:trim_mcap -- --help
bazel run //resim/utils:trim_mcap -- \
path/to/in.mcap \
path/to/out.mcap \
--start_time 1687370440.709534246 \
--end_time 1687370450.709534246
```
=> Add tool for trimming MCAP logs to an interval

resim/utils/BUILD, resim/utils/tuple_utils.hh, resim/utils/tuple_utils_test.cc
Add a `for_each_in_tuple()` function which calls a given callable function or object on each element of a given tuple.
```bash
bazel test //resim/utils:tuple_utils_test
```
=> Call a function on each element of a tuple

resim/math/is_approx.hh, resim/math/is_approx_test.cc, resim/msg/BUILD, resim/msg/fuzz_helpers.cc, resim/msg/fuzz_helpers.hh, resim/msg/fuzz_helpers_test.cc, resim/msg/odometry.proto, resim/msg/odometry_from_ros2.cc, resim/msg/odometry_from_ros2.hh, resim/msg/odometry_from_ros2_test.cc, resim/msg/pose.proto, resim/msg/pose_from_ros2.cc, resim/msg/pose_from_ros2.hh, resim/msg/pose_from_ros2_test.cc, resim/testing/BUILD, resim/testing/fuzz_helpers.cc, resim/testing/fuzz_helpers.hh
Add ROS2 converters for Pose, PoseWithCovariance, Twist, TwistWithCovariance, and Odometry.
```bash
bazel test //resim/msg:pose_from_ros2_test
bazel test //resim/msg:odometry_from_ros2_test
```
=> Add Pose and Odometry Converters

resim/geometry/proto/BUILD, resim/geometry/proto/fuzz_helpers.cc, resim/geometry/proto/fuzz_helpers.hh, resim/geometry/proto/fuzz_helpers_test.cc, resim/geometry/proto/oriented_box.proto, resim/msg/BUILD, resim/msg/fuzz_helpers.cc, resim/msg/fuzz_helpers.hh, resim/msg/oriented_box_from_ros2.cc, resim/msg/oriented_box_from_ros2.hh, resim/msg/oriented_box_from_ros2_test.cc, resim/transforms/proto/BUILD, resim/transforms/proto/fuzz_helpers.cc, resim/transforms/proto/fuzz_helpers.hh, resim/transforms/proto/fuzz_helpers_test.cc
Add ROS2 Converters for Oriented Boxes
```bash
bazel test //resim/msg:oriented_box_from_ros2_test
bazel test //resim/transforms/proto:fuzz_helpers_test
bazel test //resim/geometry/proto:fuzz_helpers_test
bazel test //resim/msg:fuzz_helpers_test
```
=> Oriented Box ROS2 converters

deps.bzl, resim/third_party/mcap/mcap.BUILD
Upgrade our MCAP dependency to a more recent version.
```bash
full_test () {                                                                                                       
TARGET="$1"                                                                                                       
VALGRIND="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1" 
bazel test --runs_per_test=100 "${TARGET}" && \                                                                   
bazel test --test_timeout=3600 --run_under="${VALGRIND}" "${TARGET}" --test_output=all                            
}
full_test //resim/utils:mcap_logger_test
```
=> Upgrade our MCAP Dependency

docs/resim/curves/index.md, resim/msg/converter_plugin.hh, resim/msg/default_converter_plugin.cc, resim/msg/default_converter_plugin_test.cc, resim/msg/detection.proto, resim/msg/detection_from_ros2.cc, resim/msg/detection_from_ros2.hh, resim/msg/detection_from_ros2_test.cc, resim/msg/fuzz_helpers.cc, resim/msg/fuzz_helpers.hh, resim/msg/fuzz_helpers_test.cc
Make it so we can convert `vision_msgs/msg/Detection3DArray` messages.
Prev PRs:
- #32
```
bazel test //resim/msg/...
```
=> Add detection arrays as a convertible type

resim/msg/detection.proto, resim/msg/detection_from_ros2.cc, resim/msg/fuzz_helpers.cc, resim/msg/fuzz_helpers.hh, resim/msg/fuzz_helpers_test.cc
Add an ID field to 3D detections to more closely match [vision_msgs::msg::Detection3D](https://github.com/ros-perception/vision_msgs/blob/ros2/vision_msgs/msg/Detection3D.msg).
```bash
bazel test //resim/msg/...
```
=> Add id field to 3D detections

deps.bzl, resim/msg/BUILD, resim/toolchain/check_python_test.py, transitive_deps.bzl
Upgrade rules_python and protobuf so we can set up protobuf generated python.
```
bazel build //resim/msg/...
```
=> Set up protobuf generated python

resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto
Introduces an optional field that acts as an ordering hint when metrics are displayed or combined.
=> Ordering Field for Metrics

.trunk/config/.pylintrc
Add pylint exemptions to trunk for warnings we're not concerned with.
```bash
trunk check
```
=> Adjustments to pylint exemptions in trunk

transitive_deps.bzl
Add the needed prefix to the requireents_lock target which causes failures in dependent repos if not present. A short explanation: Without the prefix, dependent repos look for requirements_lock.txt in their own workspace which is not the desired behavior.
* Change one of our dependent repos to depend on this branch.
* Verify that things now work as expected.
=> Add the required prefix to the requirements_lock target

resim/ros2/BUILD, resim/ros2/converter_plugin_helpers.hh, resim/ros2/default_converter_plugin.cc
Factor some of the default converter plugin functions out into a header so they can be used when defining other plugins.
```bash
bazel test //resim/ros2:default_converter_plugin_test
```
=> Add converter plugin helpers

.trunk/trunk.yaml, resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/proto/validate_metrics_proto_test.py, resim/metrics/python/metrics_utils.py, resim/metrics/python/metrics_utils_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py
Adds a new failure status, representing BLOCKING failure, making the current default status a WARNING fail. 
(WARNING: temporarily disables mypy as it's failing, and blocking future work.)
`bazel test //resim/metrics/...`
=> Add new BLOCK failure status

resim/metrics/python/metrics.py, resim/metrics/python/metrics_utils.py
Some comments which existed to make mypy pass now cause `trunk check` to fail on releases, as `mypy` is temporarily disabled. We therefore (again, probably temporarily) remove those comments.
`trunk check`
=> Remove mypy comments so trunk check on release passes

pkg/BUILD, resim/geometry/BUILD, resim/geometry/polygon_distance.cc, resim/geometry/polygon_distance.hh, resim/geometry/polygon_distance_test.cc, resim/geometry/polygon_utils.cc, resim/geometry/polygon_utils.hh, resim/geometry/polygon_utils_test.cc, resim/geometry/python/BUILD, resim/geometry/python/polygon_distance.cc, resim/geometry/python/polygon_distance_python.cc, resim/geometry/python/polygon_distance_test.py, resim/math/BUILD, resim/math/clamp.hh, resim/math/clamp_test.cc
Add a function to compute the distance between convex polygons.
```bash
bazel test //resim/geometry:polygon_distance_test
bazel test //resim/geometry:polygon_utils_test
```
=> Add polygon utils and distance function

pkg/BUILD, resim/transforms/proto/BUILD, version.bzl
Prepare to release framed vector's python proto bindings from open core as we'd like to use them elsewhere.
```bash
bazel build //pkg:msg_wheel
pushd bazel-bin/pkg
unzip resim_msg-0.0.5-py3-none-any.whl
popd
```
Verify the newly released files are there:
```
inflating: resim/msg/detection_pb2.py  
inflating: resim/msg/header_pb2.py  
inflating: resim/msg/navsat_pb2.py  
inflating: resim/msg/odometry_pb2.py  
inflating: resim/msg/pose_pb2.py   
inflating: resim/msg/transform_pb2.py  
inflating: resim/transforms/proto/frame_3_pb2.py  
inflating: resim/transforms/proto/framed_vector_3_pb2.py  
inflating: resim/transforms/proto/se3_pb2.py  
inflating: resim_msg-0.0.3.dist-info/WHEEL  
inflating: resim_msg-0.0.3.dist-info/METADATA  
inflating: resim_msg-0.0.3.dist-info/RECORD  
```
=> Prepare to release framed vector in v0.0.5

resim/geometry/BUILD, resim/geometry/polygon_distance.cc, resim/geometry/polygon_distance_test.cc
We don't want to be as stringent here. Better to just warn the user about the shortcoming.
```bash
bazel test //resim/geometry:polygon_distance_test
```
=> Allow the polygon distance function to fail gracefully

resim/ros2/BUILD, resim/ros2/converter_plugin.cc, resim/ros2/converter_plugin.hh, resim/ros2/converter_plugin_test.cc, resim/ros2/default_converter_plugin_test.cc, resim/ros2/resim_log_from_ros2.cc, resim/ros2/resim_log_from_ros2_test.cc, resim/ros2/resim_log_from_ros2_test_helpers.cc, resim/ros2/testing/BUILD, resim/ros2/testing/resim_log_from_ros2_test_converter_plugin.cc
In some cases, we encounter old/invalid messages in a rosbag that we don't care about. We don't want these to crash the converter script so we now warn instead of crashing.
```
bazel test //resim/ros2/...
```
=> Allow ROS2 converter script to fail gracefully

resim/msg/BUILD, resim/msg/byte_swap_helpers.cc, resim/msg/byte_swap_helpers.hh, resim/msg/byte_swap_helpers_test.cc, resim/msg/fuzz_helpers.cc, resim/msg/fuzz_helpers.hh, resim/msg/fuzz_helpers_test.cc, resim/msg/primitives.proto, resim/ros2/BUILD, resim/ros2/primitives_from_ros2.cc, resim/ros2/primitives_from_ros2.hh, resim/ros2/primitives_from_ros2_test.cc
Add primitive message types and ROS2 converters for them.
```
bazel test //resim/msg:byte_swap_helpers_test
bazel test //resim/msg:fuzz_helpers_test
bazel test //resim/ros2:primitives_from_ros2_test
```
=> Add ROS2 converters for primitive types

resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/proto/validate_metrics_proto_test.py, resim/metrics/python/metrics_utils.py, resim/metrics/python/metrics_utils_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py
Reverts resim-ai/open-core#91
Adds a new failure status, representing BLOCKING failure, making the current default status a WARNING fail. 
`bazel test //resim/metrics/...`
=> Revert "Revert "Add new BLOCK failure status""

resim/testing/BUILD, resim/testing/fuzz_helpers.hh, resim/testing/fuzz_helpers_test.cc
Add fuzz helpers for vectors of type T, assuming that T itself has fuzz helpers.
```bash
bazel test //resim/testing:fuzz_helpers_test
```
=> Add vector fuzz helpers

deps.bzl
Upgrade the dependency on foxglove schemas to get new message types, including FrameTransforms.
```bash
bazel test //resim/visualization/...
```
=> Upgrade foxglove schemas dependency

resim/visualization/foxglove/BUILD, resim/visualization/foxglove/line_primitive_options.hh
Add the line primitive options struct from our private repository.
```
bazel build //resim/visualization/foxglove:line_primitive_options
```
=> Add line primitive options struct

pkg/BUILD, resim/actor/state/proto/BUILD
Include the observable state proto message type in the msg wheel since it's used for actor states.
```bash
bazel build //pkg:msg_wheel
```
=> Include observable state proto message type in resim-msg wheel

pkg/BUILD, resim/transforms/python/BUILD, resim/transforms/python/geodetic_python.cc, resim/transforms/python/geodetic_python_test.py
Add pybindings for geodetic libraries.
```bash
bazel test //resim/transforms/python:geodetic_python_test
```
=> Add pybindings for geodetics

deps.bzl, resim/metrics/fetch_all_pages.py, resim/metrics/fetch_job_metrics.py, resim/metrics/fetch_job_metrics_test.py, resim/metrics/fetch_metrics_urls.py, resim/metrics/fetch_metrics_urls_test.py
Upgrade batch metrics fetching code to work with project ids in the endpoint as part of the global project migration.
```bash
bazel test //resim/metrics:fetch_job_metrics_test
bazel test //resim/metrics:fetch_metrics_urls_test
```
Run this script against the real staging api:
https://github.com/resim-ai/open-core/blob/prod/mikebauer/project-batch-metrics-test/resim/metrics/test.py
=> Global Projects Migration

docs/resim/utils/output_parameters.md, resim/dynamics/forward_euler.hh, resim/dynamics/integrator.hh, resim/dynamics/integrator_test.cc, resim/dynamics/rigid_body/gravity_test.cc, resim/examples/output_parameters.cc, resim/math/newton_solver.hh, resim/math/newton_solver_test.cc, resim/planning/ilqr.hh, resim/planning/ilqr_test.cc, resim/transforms/geodetic.cc, resim/transforms/geodetic_test.cc, resim/utils/nullable_reference.hh, resim/utils/nullable_reference_test.cc
Add a special type for null references which is implicitly convertible to any NullableReference<T>. This is analogous to `std::nullopt_t` and works the same way.
```bash
bazel test //resim/utils:nullable_reference_test
```
=> Add special type for null references

pkg/BUILD
Make sure that ROS2 primitive message types are in our messages wheel.
```bash
bazel build //pkg/...
```
And verify that the msg wheel has the new library in it.
=> Release primitive ros2 types in python

resim/dynamics/rigid_body/dynamics.cc, resim/dynamics/rigid_body/dynamics_test.cc
Satisfy an old TODO by adding diffs for rigid body dynamics.
```bash
bazel test --test_output=all  //resim/dynamics/rigid_body:dynamics_test
```
=> Add diffs to rigid body dynamics

resim/metrics/fetch_job_metrics.py, resim/metrics/fetch_job_metrics_test.py
Currently, only the first page of job metrics is being checked. This doesn't work for batches with more than 10 jobs. Fetch all pages.
```bash
bazel test //resim/metrics:fetch_job_metrics_test
```
=> Fix pagination bug in fetch_job_metrics_by_batch()

resim/planning/drone/BUILD, resim/planning/drone/state.cc, resim/planning/drone/state.hh, resim/planning/drone/state_test.cc
Add a state type for model predictive control of drone motion including the drone's position, orientation, velocity, and angular velocity.
```bash
bazel test //resim/planning/drone:state_test
```
=> Add a state type for mpc on drone motion

resim/visualization/log/BUILD, resim/visualization/log/extract_experience.cc, resim/visualization/log/extract_experience.hh, resim/visualization/log/extract_experience_test.cc, resim/visualization/log/make_visualization_log.cc, resim/visualization/log/test_helpers.cc, resim/visualization/log/test_helpers.hh, resim/visualization/log/test_helpers_test.cc, resim/visualization/log/visit_topic.cc, resim/visualization/log/visit_topic.hh, resim/visualization/log/visit_topic_test.cc, resim/visualization/log/visualize_actor_states.cc, resim/visualization/log/visualize_actor_states.hh, resim/visualization/log/visualize_actor_states_test.cc
Add log visualization tools to open-core.
```bash
bazel test //resim/visualization/log/...
```
=> Add log visualization tools

resim/experiences/proto/BUILD
Add proto bindings for experiences so they can be read in metrics runners.
```bash
bazel build //resim/experiences/proto:experience_proto_py
```
=> Add proto bindings for experience

resim/metrics/proto/BUILD, resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/python/BUILD, resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py, resim/metrics/python/unpack_metrics.py
Extends the ReSim metrics schema to support storing a serialized plotly chart or an arbitrary image.
```
```
=> Image and Plotly Metrics

resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py, resim/metrics/python/metrics_utils.py, resim/metrics/python/metrics_utils_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py, resim/metrics/python/unpack_metrics.py, resim/metrics/python/unpack_metrics_test.py
Extends the metrics SDK to support events.
```
```
=> Events SDK

deps.bzl, resim/metrics/proto/BUILD, resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/proto/validate_metrics_proto_test.py, resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py, resim/metrics/python/metrics_utils.py, resim/metrics/python/metrics_utils_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py, resim/metrics/python/unpack_metrics.py, resim/metrics/python/unpack_metrics_test.py
Extends the ReSim Metrics schema with a list of events, which can reference metrics defined in the metrics collection. This PR also introduces the required changes to the validator to support event validation.
the metrics SDK is updated to support events. 
```
```
=> Event Metrics and Validation

resim/auth/python/BUILD, resim/auth/python/check_expiration.py, resim/auth/python/check_expiration_test.py, resim/auth/python/device_code_client.py, resim/auth/python/device_code_client_test.py
Make sure that the directory where we cache python credentials exists and also record the absolute expiration time in the cached token so we can refresh it when the time comes.
```
bazel test //resim/auth/python/...
```
=> Fix python auth missing directory & expired tokens

resim/metrics/fetch_metrics_urls.py, resim/metrics/fetch_metrics_urls_test.py
Currently the metrics data urls for external file metrics are just the original files themselves. These obviously can't be unpacked as protobuf message types in the same was as the other metrics data, so we omit them for now to allow `fetch_job_metrics` to function properly.
```bash
bazel test //resim/metrics:fetch_metrics_urls_test
```
=> Don't fetch external file metrics data

resim/converter/parser.hh, resim/converter/parser_test.cc
Currently the macro used to define a "Plain-Old-Data" (POD) getter for POD structs doesn't allow mutable access to the contents of the struct even if the struct is mutable. This is due to the way in which `decltype()` functions. Particularly "unparenthesized class member access expression[s]" cause decltype to get the declared value of the field being accessed which is generally not a reference. We use parentheses to ameliorate this. See
[here](https://en.cppreference.com/w/cpp/language/decltype) for more details. We also added some tests to confirm this now works.
```bash
bazel test //resim/converter:parser_test
```
=> Make pod parser mutable

.trunk/trunk.yaml, resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py
It's very easy to accidentally pass a string to `with_tags()` and have each character of the string become its own tag.
```bash
bazel test //resim/metrics/python:metrics_test
```
=> Guard against bugs where strings are passed to with_tags()

.devcontainer/Dockerfile, BUILD, MODULE.bazel, pkg/BUILD, resim/ros2/primitives_from_ros2.cc, resim/toolchain/BUILD, resim/toolchain/cc_toolchain_config.bzl
This will allow us to start releasing python wheels for aarch64/arm64 platforms.
```
./.devcontainer/build.sh
./.devcontainer/run_local.sh
bazel test --action_env "QEMU_LD_PREFIX=/usr/aarch64-linux-gnu/" --run_under "qemu-aarch64"  --platforms "//:aarch64_linux" //resim/toolchain:check_compiler_test
```
=> Add toolchain to cross compile for aarch64

pkg/BUILD, resim/orchestration/BUILD, resim/orchestration/kickoff_report.py, resim/orchestration/kickoff_report_test.py, resim/orchestration/resim_python_client_mocks.py, resim/orchestration/resim_python_client_mocks_test.py
Add a helper function which allows us to kickoff a report easily based on a batch id and a test suite allowlist. The idea is we can use this to automatically kick of reports as the last step of batch metrics.
Also add mocks for the API client so we don't have to hit the API to test this. The expectation is that this mocks library will grow as more endpoints require mocking.
```bash
bazel test //resim/orchestration/...
```
=> Add helper to kickoff a report based off of a test suite name

resim/dynamics/rigid_body/BUILD, resim/dynamics/rigid_body/dynamics.cc, resim/dynamics/rigid_body/state.cc, resim/dynamics/rigid_body/state.hh, resim/dynamics/rigid_body/state_test.cc
This is a ReSurrection of an old PR on a previous version of this repo.
Add getters which allow packing and unpacking of rigid body state deltas to be accomplished more explicitly without having to use head and tail frequently.
```bash
bazel test //resim/dynamics/rigid_body/...
```
=> Make packing/unpacking rigid body state deltas more explicit

.bazelrc
Trunk as well as other tools often modify the $PATH when using bazel which causes "costly cache misses". This makes it necessary to rebuild dependencies more frequently than should be required. See [here](https://docs.aspect.build/guides/bazelrc/) for a brief explanation. We should maybe consider some of the other flags from there too.
```
bazel build //...
```
Change PATH and verify that rebuilds are no longer required.
=> Reduce cache misses with --incompatible_strict_action_env

MODULE.bazel, resim/toolchain/BUILD, resim/toolchain/cc_toolchain_config.bzl
Add an aarch64 toolchain for use on ubuntu.
On a mac (in an ubuntu docker container):
```
```
=> Add aarch64 toolchain

resim/metrics/default_report_metrics.py
Use a semaphore to limit the number of concurrent endpoint calls in the default report metrics.
Run against a large report which is known to be problematic.
=> Limit number of concurrent endpoint calls in report metrics

requirements.txt, requirements_lock.txt
Make sure that our python dependencies are compatible with resim-python-client.
Build the wheel locally and check that it can be included alongside the latest `resim-python-client` version with `pip-compile`.
=> Make python dependencies compatible with resim-python-client

docs/resim/metrics/metrics_writer.md, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py
This PR proposes to extend the ReSim Metrics Writer to enable the passing through of a MetricsStatus that would override the default calculation for how an overall test status is calculated. It enables users flexibility to determine exactly how a test would fail based on the metrics it contains. For example, warnings could be ignored, rather than cause the whole test to be considered in a warning status.
```
```
=> Introduce Metrics Status Override

resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py, resim/metrics/python/unpack_metrics.py
Add a project id to the batchwise bar chart metric to make rendering easier.
```
bazel test //resim/metrics/...
```
=> Add project id to BatchwiseBarChartMetric

resim/metrics/default_report_metrics.py
To help with the issue of the status bar charts becoming unreadable when there are high numbers of batches, display it as a categorical bar chart instead.
Generate a metrics.binproto with this locally and try it in the metrics debugger.
=> Display test_status_over_time as a categorical bar chart

resim/metrics/BUILD, resim/metrics/fetch_job_metrics.py, resim/metrics/fetch_job_metrics_test.py
Currently, fetching image metrics fails in fetch_job_metrics since image metrics depend on external file metrics data, which we don't fetch since they don't have a protobuf message.
Try running fetch_job_metrics_for_batch() on an existing batch.
=> Fix fetch fetch job metrics

resim/metrics/proto/generate_test_metrics.py, resim/metrics/proto/metrics.proto, resim/metrics/proto/validate_metrics_proto.py, resim/metrics/python/metrics.py, resim/metrics/python/metrics_test.py, resim/metrics/python/metrics_writer.py, resim/metrics/python/metrics_writer_test.py, resim/metrics/python/unpack_metrics.py
Extends the ReSim Metrics SDK with a 'Text Metric', which aims solely to display markdown as a metric.
```
```
=> Text Metrics

.github/workflows/lint-and-codecov.yml, BUILD, bazel/python.bzl, pkg/BUILD
Add the needed config settings so that we don't try to generate python stubs from cross-compiled pybindings.
Splice the cross-compilation step of the release temporarily into the lint and codecov CI run for this branch:
https://github.com/resim-ai/open-core/actions/runs/12838210087/job/35803390912?pr=217
=> Only build stubs on host

resim/geometry/BUILD, resim/geometry/box_box_distance.cc, resim/geometry/box_box_distance.hh, resim/geometry/box_box_distance_test.cc, resim/geometry/boxes_collide.cc, resim/geometry/boxes_collide.hh
Factor out parts of the box collision check into a distance function for two oriented boxes. Also fix a bug in that function relating to how distances are handled.
```
bazel test //resim/geometry:box_box_distance_test
```
=> Add box-box distance function

.trunk/.gitignore, .trunk/trunk.yaml, pkg/BUILD, resim-python-client/README.md, resim/auth/python/BUILD, resim/auth/python/const.py, resim/auth/python/device_code_client.py, resim/auth/python/device_code_client_test.py, resim/auth/python/username_password_client.py, resim/auth/python/username_password_client_test.py
- Adds a UsernamePasswordClient for authenticating in CI
- Adds a readme for the Python client to help users get to using it.
=> Add UsernamePasswordClient and document usage of client

resim/curves/learning/BUILD, resim/curves/learning/two_jet_mean.cc, resim/curves/learning/two_jet_mean.hh, resim/curves/learning/two_jet_mean_test.cc, resim/curves/optimization/BUILD
Two Jets exist on a manifold so their mean $\mu$ is computed iteratively such that:
$$
\sum_i (x_i \ominus \mu) = 0
$$
In our case $\ominus$ is defined by the difference in [two_jet_tangent_space](https://github.com/resim-ai/open-core/blob/main/resim/curves/optimization/two_jet_tangent_space.hh).
```bash
bazel test //resim/curves/learning/...
```
=> Add two jet mean function

pkg/BUILD, resim/metrics/python/BUILD, resim/metrics/python/emissions.py, resim/metrics/python/emissions_test.py, resim/metrics/python/metrics_utils.py, resim/metrics/python/metrics_utils_test.py
- Adds an `emit` function to be used with the upcoming Metrics V2 update
=> Add metrics v2 `emit` function

docs/resim/index.md, docs/resim/metrics/metrics_builds.md
Clarify some finer points in the documentation as flagged by customers
=> Clarify supported python versions and folder structure for metrics builds

docs/resim/metrics/metric_types.md
We are moving our charting library to Plotly, and are deprecating metrics that used Rechart. This PR does a couple of things: 
To test you can pull it locally and run it and see if things look good.
=> Deprecating Rechart in metrics

pkg/BUILD, resim/metrics/BUILD, resim/metrics/fetch_sweep_metrics.py
Add a helper binary to fetch a DataFrame with all scalar job metrics from a parameter sweep.
```bash
bazel run //resim/metrics:fetch_sweep_metrics -- --project-id <project-id> --sweep-id <sweep-id> --output-path "$(pwd)/metrics.csv"
```
Running against one of our test projects, with pivot:
|batch_id                            |job_id                              |velocity_cost_override|Mean Ego Speed    |TestLength  |
|------------------------------------|------------------------------------|----------------------|------------------|------------|
|24c09aa0-4e78-44cb-922d-7296315427b8|10607d7b-61f3-42aa-a674-65148739a8e8|0.06                  |19.177305066641562|19.915033869|
|7d63821f-8100-4a29-8544-a012ef930f41|508f9572-3764-42aa-ba5c-10bc93bd493d|0.01 …
=> Sweep metrics collector script

resim/metrics/fetch_job_metrics.py, resim/metrics/fetch_job_metrics_test.py
This metric references external files which aren't pulled when fetching job metrics, so the function will fail when trying to unpack image list metrics if they aren't exempted.
```bash
bazel test //resim/metrics:fetch_job_metrics_test
```
=> Don't fetch image list metrics in fetch_job_metrics
